# Ingestion and Lots of Data Preparation

In [1]:
import pandas
from pandas import Series, DataFrame

In [2]:
dataA = pandas.read_excel('Teens_Gaming_2008.xlsx', 'Teens_Gaming_2008',)
dataA.head()
    

psraid    weight  int_date tz  cregion   fips  state    msa usr  usr1  \
0     634  4.000000    110707  E        1  34017     34  35620   S     2   
1   16854  1.333333     12408  E        1  34003     34  35620   S     2   
2   14856  1.937500     11808  E        1  34003     34  35620   S     2   
3   14752  1.791667     12108  E        1  34003     34  35620   S     2   
4     115  1.000000    110107  E        1  34003     34  35620   S     2   

   cstatus  p1  p2  kidage  kidgen  ...  k4cnt  k6cnt  k7cnt  k8cnt  k9cnt  \
0        2   2   1      16       1  ...    3.0      3      5      2      3   
1        1   1   1      13       2  ...    3.0      5      5      3      3   
2        0   2   2      14       1  ...    3.0      5      4      5      3   
3        2   2   1      12       1  ...    2.0      5      5      5      4   
4        2   3   1      14       1  ...    3.0      5      6      3      4   

   k14cnt  k26cnt  k29cnt  raceos  modemos               k3dos  k12os  k13os  \
0     5.0     4.0     0.0     NaN      NaN                WORK    NaN    NaN   
1     5.0     3.0     1.0     NaN      NaN        A CELL PHONE    NaN    NaN   
2     5.0     2.0     0.0     NaN      NaN                 NaN    NaN    NaN   
3    10.0     4.0     2.0     NaN      NaN                 NaN    NaN    NaN   
4     8.0     1.0     1.0     NaN      NaN  YUOR FRIENDS HOUSE    NaN    NaN   

                                        k17game  \
0                      MADDEN, NBA LIVE, NASCAR   
1            THE SIMS 2, CRAZY TAXI 4, SIM PETS   
2     CALL OF DUTY 4, GUITAR HERO 3, ORANGE BOX   
3             HALO 3, GUITAR HERO, MARIO GALAXY   
4  HALO 3, GUITER HERO, BLOON'S POWER DEFENSE 2   

                                       k28game  
0                                          NaN  
1  WORD SEARCH, BRAIN TEASERS, POLITICAL GAMES  
2                                          NaN  
3                                          NaN  
4                                          NaN  

[5 rows x 166 columns]

In [3]:
dataD = dataA[['psraid','k14a','k14b','k14c','k14d','k14e','k14f','k14g','k14h','k14i','k14j','k14k','k14l']]
dataD.head(10)

psraid  k14a  k14b  k14c  k14d  k14e  k14f  k14g  k14h  k14i  k14j  k14k  \
0     634   1.0   1.0   2.0   2.0   2.0   2.0   1.0   2.0   1.0   1.0   2.0   
1   16854   8.0   1.0   2.0   2.0   2.0   1.0   2.0   2.0   1.0   1.0   1.0   
2   14856   2.0   2.0   1.0   1.0   1.0   1.0   2.0   2.0   2.0   2.0   1.0   
3   14752   1.0   1.0   1.0   1.0   2.0   1.0   1.0   2.0   1.0   1.0   1.0   
4     115   1.0   1.0   1.0   1.0   1.0   2.0   1.0   2.0   2.0   1.0   1.0   
5    1404   2.0   1.0   1.0   1.0   1.0   1.0   2.0   1.0   1.0   2.0   2.0   
6   14866   1.0   1.0   1.0   1.0   2.0   1.0   1.0   2.0   1.0   1.0   1.0   
7    4152   2.0   2.0   2.0   2.0   2.0   1.0   2.0   2.0   2.0   2.0   2.0   
8   14797   2.0   2.0   1.0   1.0   2.0   1.0   1.0   2.0   2.0   1.0   2.0   
9   14771   1.0   2.0   1.0   1.0   1.0   2.0   2.0   2.0   2.0   2.0   1.0   

   k14l  
0   2.0  
1   2.0  
2   2.0  
3   1.0  
4   2.0  
5   2.0  
6   1.0  
7   2.0  
8   2.0  
9   2.0

In [4]:
dataD = pandas.melt(dataD, ['psraid'])
dataD.head(10)

psraid variable  value
0     634     k14a    1.0
1   16854     k14a    8.0
2   14856     k14a    2.0
3   14752     k14a    1.0
4     115     k14a    1.0
5    1404     k14a    2.0
6   14866     k14a    1.0
7    4152     k14a    2.0
8   14797     k14a    2.0
9   14771     k14a    1.0

In [5]:
dataD['value'].dtype

dtype('float64')

In [6]:
dataD.loc[dataD.value == 1, 'newValue'] = 1
dataD.loc[dataD.value != 1, 'newValue'] = 0
dataD.head(10)


psraid variable  value  newValue
0     634     k14a    1.0       1.0
1   16854     k14a    8.0       0.0
2   14856     k14a    2.0       0.0
3   14752     k14a    1.0       1.0
4     115     k14a    1.0       1.0
5    1404     k14a    2.0       0.0
6   14866     k14a    1.0       1.0
7    4152     k14a    2.0       0.0
8   14797     k14a    2.0       0.0
9   14771     k14a    1.0       1.0

In [7]:
dataD = dataD[['psraid','variable','newValue']].dropna()
dataD.head(10)

psraid variable  newValue
0     634     k14a       1.0
1   16854     k14a       0.0
2   14856     k14a       0.0
3   14752     k14a       1.0
4     115     k14a       1.0
5    1404     k14a       0.0
6   14866     k14a       1.0
7    4152     k14a       0.0
8   14797     k14a       0.0
9   14771     k14a       1.0

Ingore this cell

In [8]:
d1 = pandas.crosstab(dataD.newValue, dataD.variable)
d1.head(10)

variable  k14a  k14b  k14c  k14d  k14e  k14f  k14g  k14h  k14i  k14j  k14k  \
newValue                                                                     
0.0        601   332   401   614   470   581   402   717   412   334   439   
1.0        501   770   701   488   632   521   700   385   690   768   663   

variable  k14l  
newValue        
0.0        784  
1.0        318

In [9]:
d2 = dataD.pivot_table(['newValue'],index=['psraid'], columns=['variable'])
d2.head(10)
list(d2.columns)

newValue                                                       
variable     k14a k14b k14c k14d k14e k14f k14g k14h k14i k14j k14k k14l
psraid                                                                  
11            1.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0  1.0  1.0  0.0  1.0
51            0.0  1.0  1.0  0.0  1.0  1.0  0.0  1.0  1.0  1.0  0.0  0.0
53            0.0  1.0  1.0  1.0  0.0  1.0  1.0  0.0  1.0  1.0  1.0  1.0
56            0.0  1.0  0.0  0.0  1.0  1.0  1.0  0.0  1.0  0.0  1.0  0.0
69            0.0  1.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  1.0  0.0
103           0.0  1.0  0.0  0.0  1.0  0.0  1.0  0.0  1.0  1.0  1.0  0.0
115           1.0  1.0  1.0  1.0  1.0  0.0  1.0  0.0  0.0  1.0  1.0  0.0
322           0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0
330           0.0  1.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0
362           1.0  0.0  0.0  1.0  0.0  0.0  1.0  1.0  0.0  1.0  1.0  0.0

[('newValue', 'k14a'),
 ('newValue', 'k14b'),
 ('newValue', 'k14c'),
 ('newValue', 'k14d'),
 ('newValue', 'k14e'),
 ('newValue', 'k14f'),
 ('newValue', 'k14g'),
 ('newValue', 'k14h'),
 ('newValue', 'k14i'),
 ('newValue', 'k14j'),
 ('newValue', 'k14k'),
 ('newValue', 'k14l')]

In [10]:
d2.columns =[s1+str(s2) for (s1,s2) in d2.columns.tolist()]
d2.head(5)


newValuek14a  newValuek14b  newValuek14c  newValuek14d  newValuek14e  \
psraid                                                                         
11               1.0           0.0           1.0           1.0           1.0   
51               0.0           1.0           1.0           0.0           1.0   
53               0.0           1.0           1.0           1.0           0.0   
56               0.0           1.0           0.0           0.0           1.0   
69               0.0           1.0           1.0           0.0           0.0   

        newValuek14f  newValuek14g  newValuek14h  newValuek14i  newValuek14j  \
psraid                                                                         
11               1.0           0.0           0.0           1.0           1.0   
51               1.0           0.0           1.0           1.0           1.0   
53               1.0           1.0           0.0           1.0           1.0   
56               1.0           1.0           0.0           1.0           0.0   
69               1.0           0.0           0.0           0.0           1.0   

        newValuek14k  newValuek14l  
psraid                              
11               0.0           1.0  
51               0.0           0.0  
53               1.0           1.0  
56               1.0           0.0  
69               1.0           0.0

In [11]:
d2.reset_index(inplace=True)
d2.head(5)

psraid  newValuek14a  newValuek14b  newValuek14c  newValuek14d  \
0      11           1.0           0.0           1.0           1.0   
1      51           0.0           1.0           1.0           0.0   
2      53           0.0           1.0           1.0           1.0   
3      56           0.0           1.0           0.0           0.0   
4      69           0.0           1.0           1.0           0.0   

   newValuek14e  newValuek14f  newValuek14g  newValuek14h  newValuek14i  \
0           1.0           1.0           0.0           0.0           1.0   
1           1.0           1.0           0.0           1.0           1.0   
2           0.0           1.0           1.0           0.0           1.0   
3           1.0           1.0           1.0           0.0           1.0   
4           0.0           1.0           0.0           0.0           0.0   

   newValuek14j  newValuek14k  newValuek14l  
0           1.0           0.0           1.0  
1           1.0           0.0           0.0  
2           1.0           1.0           1.0  
3           0.0           1.0           0.0  
4           1.0           1.0           0.0

In [12]:
d2.columns = [x.strip().replace('newValuek14', '') for x in d2.columns]
d2.head()

psraid    a    b    c    d    e    f    g    h    i    j    k    l
0      11  1.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0  1.0  1.0  0.0  1.0
1      51  0.0  1.0  1.0  0.0  1.0  1.0  0.0  1.0  1.0  1.0  0.0  0.0
2      53  0.0  1.0  1.0  1.0  0.0  1.0  1.0  0.0  1.0  1.0  1.0  1.0
3      56  0.0  1.0  0.0  0.0  1.0  1.0  1.0  0.0  1.0  0.0  1.0  0.0
4      69  0.0  1.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  1.0  0.0

In [13]:
d2.to_csv('d2.csv') 

# Now ready to do clustering method #1

In [14]:
d3 = d2.drop(['psraid'], axis=1)
d3.head(4)

a    b    c    d    e    f    g    h    i    j    k    l
0  1.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0  1.0  1.0  0.0  1.0
1  0.0  1.0  1.0  0.0  1.0  1.0  0.0  1.0  1.0  1.0  0.0  0.0
2  0.0  1.0  1.0  1.0  0.0  1.0  1.0  0.0  1.0  1.0  1.0  1.0
3  0.0  1.0  0.0  0.0  1.0  1.0  1.0  0.0  1.0  0.0  1.0  0.0

In [15]:
dataset_array = d3.values
print(dataset_array.dtype)
print(dataset_array)

float64
[[1. 0. 1. ... 1. 0. 1.]
 [0. 1. 1. ... 1. 0. 0.]
 [0. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 0. 1. 1.]
 [1. 1. 1. ... 1. 1. 0.]
 [0. 1. 0. ... 0. 1. 0.]]


In [21]:
# import statements
import sklearn
import numpy as np
import matplotlib.pyplot as plt


from https://towardsdatascience.com/an-introduction-to-clustering-algorithms-in-python-123438574097

In [22]:
# import KMeans
from sklearn.cluster import KMeans


In [23]:
# create kmeans object
kmeans = KMeans(n_clusters=4)
# fit kmeans object to data
kmeans.fit(dataset_array)
# print location of clusters learned by kmeans object
print(kmeans.cluster_centers_)
# save new clusters for chart
y_km = kmeans.fit_predict(dataset_array)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
       n_clusters=4, n_init=10, n_jobs=None, precompute_distances='auto',
       random_state=None, tol=0.0001, verbose=0)

[[0.06329114 0.63291139 0.08860759 0.06329114 0.28691983 0.25738397
  0.20253165 0.07594937 0.11814346 0.27848101 0.44725738 0.05485232]
 [0.86743516 0.73487032 0.95100865 0.79827089 0.87896254 0.66570605
  0.73487032 0.76080692 0.9481268  0.75216138 0.71757925 0.62536023]
 [0.1465798  0.8534202  0.58631922 0.06514658 0.70684039 0.59283388
  0.69055375 0.21498371 0.71009772 0.84690554 0.67100977 0.03583062]
 [0.66350711 0.48815166 0.8056872  0.83412322 0.19905213 0.22274882
  0.87677725 0.17535545 0.5450237  0.85781991 0.48341232 0.36492891]]


In [24]:
plt.scatter(points[y_km ==0,0], points[y_km == 0,1], s=100, c='red')
plt.scatter(points[y_km ==1,0], points[y_km == 1,1], s=100, c='black')
plt.scatter(points[y_km ==2,0], points[y_km == 2,1], s=100, c='blue')
plt.scatter(points[y_km ==3,0], points[y_km == 3,1], s=100, c='cyan')

NameError: name 'points' is not defined

# Now trying clustering method #2

In [ ]:
import random

In [ ]:
# https://github.com/joelgrus/data-science-from-scratch/blob/master/scratch/linear_algebra.py



class KMeans2:
    """performs k-means clustering"""
    
    def __init__(self, k):
        self.k = k #number of clusters
        self.means = None #means of clusters
    
    def classify(self,input):
        """return the index of the cluster closest to the input"""
        return min (range(self.k),
                    key = lambda i: squared_distance(input, self.means[i]))
    
    def train(self, inputs):
        # choose K random points as the initial means
        self.means = random.sample(list(inputs), self.k)
        assignments = None
        
        while True:
            #find new assignments
            new_assignments = map(self.classify, inputs)
            
            #if no assignments have changed, we're done.
            if assignments == new_assignments:
                return
            
            #otherwise keep the new assignments,
            assignments = new_assignments
            
            #And comput new means based on the new assignments
            for i in range(self.k):
                #find all the points assigned to cluster i
                i_points = [p for p, a in zip(inputs, assignments) if a==i]
                
                #make sure i_points is not zero so don't divide by 0
                if i_points:
                    self.means[i] = vector_mean(i_points)
                 
                    
    

In [ ]:
# https://github.com/joelgrus/data-science-from-scratch/blob/master/scratch/linear_algebra.py


from typing import List

Vector = List[float]

height_weight_age = [70,  # inches,
                     170, # pounds,
                     40 ] # years

grades = [95,   # exam1
          80,   # exam2
          75,   # exam3
          62 ]  # exam4

def add(v: Vector, w: Vector) -> Vector:
    """Adds corresponding elements"""
    assert len(v) == len(w), "vectors must be the same length"

    return [v_i + w_i for v_i, w_i in zip(v, w)]

assert add([1, 2, 3], [4, 5, 6]) == [5, 7, 9]

def subtract(v: Vector, w: Vector) -> Vector:
    """Subtracts corresponding elements"""
    assert len(v) == len(w), "vectors must be the same length"

    return [v_i - w_i for v_i, w_i in zip(v, w)]

assert subtract([5, 7, 9], [4, 5, 6]) == [1, 2, 3]

def vector_sum(vectors: List[Vector]) -> Vector:
    """Sums all corresponding elements"""
    # Check that vectors is not empty
    assert vectors, "no vectors provided!"

    # Check the vectors are all the same size
    num_elements = len(vectors[0])
    assert all(len(v) == num_elements for v in vectors), "different sizes!"

    # the i-th element of the result is the sum of every vector[i]
    return [sum(vector[i] for vector in vectors)
            for i in range(num_elements)]

assert vector_sum([[1, 2], [3, 4], [5, 6], [7, 8]]) == [16, 20]

def scalar_multiply(c: float, v: Vector) -> Vector:
    """Multiplies every element by c"""
    return [c * v_i for v_i in v]

assert scalar_multiply(2, [1, 2, 3]) == [2, 4, 6]

def vector_mean(vectors: List[Vector]) -> Vector:
    """Computes the element-wise average"""
    n = len(vectors)
    return scalar_multiply(1/n, vector_sum(vectors))

assert vector_mean([[1, 2], [3, 4], [5, 6]]) == [3, 4]

def dot(v: Vector, w: Vector) -> float:
    """Computes v_1 * w_1 + ... + v_n * w_n"""
    assert len(v) == len(w), "vectors must be same length"

    return sum(v_i * w_i for v_i, w_i in zip(v, w))

assert dot([1, 2, 3], [4, 5, 6]) == 32  # 1 * 4 + 2 * 5 + 3 * 6

def sum_of_squares(v: Vector) -> float:
    """Returns v_1 * v_1 + ... + v_n * v_n"""
    return dot(v, v)

assert sum_of_squares([1, 2, 3]) == 14  # 1 * 1 + 2 * 2 + 3 * 3

import math

def magnitude(v: Vector) -> float:
    """Returns the magnitude (or length) of v"""
    return math.sqrt(sum_of_squares(v))   # math.sqrt is square root function

assert magnitude([3, 4]) == 5

def squared_distance(v: Vector, w: Vector) -> float:
    """Computes (v_1 - w_1) ** 2 + ... + (v_n - w_n) ** 2"""
    return sum_of_squares(subtract(v, w))

def distance(v: Vector, w: Vector) -> float:
    """Computes the distance between v and w"""
    return math.sqrt(squared_distance(v, w))


def distance(v: Vector, w: Vector) -> float:  # type: ignore
    return magnitude(subtract(v, w))

# Another type alias
Matrix = List[List[float]]

A = [[1, 2, 3],  # A has 2 rows and 3 columns
     [4, 5, 6]]

B = [[1, 2],     # B has 3 rows and 2 columns
     [3, 4],
     [5, 6]]

from typing import Tuple

def shape(A: Matrix) -> Tuple[int, int]:
    """Returns (# of rows of A, # of columns of A)"""
    num_rows = len(A)
    num_cols = len(A[0]) if A else 0   # number of elements in first row
    return num_rows, num_cols

assert shape([[1, 2, 3], [4, 5, 6]]) == (2, 3)  # 2 rows, 3 columns

def get_row(A: Matrix, i: int) -> Vector:
    """Returns the i-th row of A (as a Vector)"""
    return A[i]             # A[i] is already the ith row

def get_column(A: Matrix, j: int) -> Vector:
    """Returns the j-th column of A (as a Vector)"""
    return [A_i[j]          # jth element of row A_i
            for A_i in A]   # for each row A_i

from typing import Callable

def make_matrix(num_rows: int,
                num_cols: int,
                entry_fn: Callable[[int, int], float]) -> Matrix:
    """
    Returns a num_rows x num_cols matrix
    whose (i,j)-th entry is entry_fn(i, j)
    """
    return [[entry_fn(i, j)             # given i, create a list
             for j in range(num_cols)]  #   [entry_fn(i, 0), ... ]
            for i in range(num_rows)]   # create one list for each i

def identity_matrix(n: int) -> Matrix:
    """Returns the n x n identity matrix"""
    return make_matrix(n, n, lambda i, j: 1 if i == j else 0)

assert identity_matrix(5) == [[1, 0, 0, 0, 0],
                              [0, 1, 0, 0, 0],
                              [0, 0, 1, 0, 0],
                              [0, 0, 0, 1, 0],
                              [0, 0, 0, 0, 1]]

data = [[70, 170, 40],
        [65, 120, 26],
        [77, 250, 19],
        # ....
       ]

friendships = [(0, 1), (0, 2), (1, 2), (1, 3), (2, 3), (3, 4),
               (4, 5), (5, 6), (5, 7), (6, 8), (7, 8), (8, 9)]

#            user 0  1  2  3  4  5  6  7  8  9
#
friend_matrix = [[0, 1, 1, 0, 0, 0, 0, 0, 0, 0],  # user 0
                 [1, 0, 1, 1, 0, 0, 0, 0, 0, 0],  # user 1
                 [1, 1, 0, 1, 0, 0, 0, 0, 0, 0],  # user 2
                 [0, 1, 1, 0, 1, 0, 0, 0, 0, 0],  # user 3
                 [0, 0, 0, 1, 0, 1, 0, 0, 0, 0],  # user 4
                 [0, 0, 0, 0, 1, 0, 1, 1, 0, 0],  # user 5
                 [0, 0, 0, 0, 0, 1, 0, 0, 1, 0],  # user 6
                 [0, 0, 0, 0, 0, 1, 0, 0, 1, 0],  # user 7
                 [0, 0, 0, 0, 0, 0, 1, 1, 0, 1],  # user 8
                 [0, 0, 0, 0, 0, 0, 0, 0, 1, 0]]  # user 9

assert friend_matrix[0][2] == 1, "0 and 2 are friends"
assert friend_matrix[0][8] == 0, "0 and 8 are not friends"

# only need to look at one row
friends_of_five = [i
                   for i, is_friend in enumerate(friend_matrix[5])
                   if is_friend]

In [ ]:
def squared_clustering_errors(inputs, k):
    """find the total squared error from k-means clustering the inputs"""
    clusterer = KMeans2(k)
    clusterer.train(inputs)
    means = clusterer.means
    assignments = map(clusterer.classify, inputs)

    return sum(squared_distance(input, means[cluster])
               for input, cluster in zip(inputs, assignments))

               
    

In [ ]:
clusterer = KMeans2(5)

In [ ]:
clusterer.train(dataset_array)

See also
 https://towardsdatascience.com/an-introduction-to-clustering-algorithms-in-python-123438574097
